[package]
name = "string-operations"
version = "0.1.0"
authors = ["İsmail Hakkı Tekin <ihakkitekin@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.0-alpha.4"
tokio = "1.8.4"
lazy_static = "1.4.0"
regex = "1.3.1"
chrono = "0.4.10"
