version: '3.1'
services:
  rust-hyper:
    build:
      context: rust/hyper
      dockerfile: Dockerfile
    ports:
      - ${RUST_PORT}:8080
  go-std:
    build:
      context: go/std
      dockerfile: Dockerfile
    ports:
      - ${GO_PORT}:8080
  javascript-nodejs:
    build:
      context: javascript/nodejs
      dockerfile: Dockerfile
    ports:
      - ${NODEJS_PORT}:8080