version: '3.1'
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    links: 
      - "rust:rust-server"
      - "go:go-server"
      - "nodejs:nodejs-server"
  rust:
    build:
      context: rust
      dockerfile: Dockerfile
    ports:
      - ${RUST_PORT}:8080
    environment:
      PROXY_URL: ${PROXY_URL} # with http/https
  go:
    build:
      context: go
      dockerfile: Dockerfile
    ports:
      - ${GO_PORT}:8080
    environment:
      PROXY_URL: ${PROXY_URL} # with http/https
  nodejs:
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - ${NODEJS_PORT}:8080
    environment:
      PROXY_URL: ${NODEJS_PROXY_URL} # without http/https