version: '3.1'
services:
  rust:
    build:
      context: rust
      dockerfile: Dockerfile
    ports:
      - ${RUST_PORT}:8080
    environment:
      PROXY_URL: ${PROXY_URL} # with http/https
  go:
    build:
      context: go
      dockerfile: Dockerfile
    ports:
      - ${GO_PORT}:8080
    environment:
      PROXY_URL: ${PROXY_URL} # with http/https
  nodejs:
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - ${NODEJS_PORT}:8080
    environment:
      PROXY_URL: ${NODEJS_PROXY_URL} # without http/https